
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="enchantment_enhancements" #mandatory
version="1.16.5-1.0.0" #mandatory
displayName="Enchantment Enhancements" #mandatory
logoFile="enchantment_enhancements.png" #optional
authors="ISenseHostility" #optional
description='''
Enchantment Enhancements adds a few new curses and enchantments to expand the vanilla set.
'''
